@api=http://localhost:8080/v1/restaurant
POST {{api}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjMsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY2MjQ1NTU3NSwiaWF0IjoxNjYyMzY5MTc1fQ.OHqBesJvDAwLbLBrRm8IUskS8psYtC3S6cZpMWOjEic

{
    "name":"1",
    "addr":"here",
    "logo":{
        "url":"nothing.com",
        "height": 1,
        "width" : 2
    },
    "cover":[
        {
        "url":"nothing.com",
        "height": 1,
        "width" : 2
    }
    ]
}
#######

GET {{api}}/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjEsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY2MjY4ODI5OCwiaWF0IjoxNjYyNjAxODk4fQ.MQPIUZX1gskqngsGvvBg-HQBsVpLFVvIBHAnkNF5jcs
####
GET {{api}}?cursor=&limit=23 HTTP/1.1
Content-Type: application/json

#########
DELETE {{api}}/e532qos8jjM2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjMsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY2MjQ1NTU3NSwiaWF0IjoxNjYyMzY5MTc1fQ.OHqBesJvDAwLbLBrRm8IUskS8psYtC3S6cZpMWOjEic
#####
GET http://localhost:8080/static////////1//1.txt

####
POST http://localhost:8080/v1/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test.jpg"
Content-Type: image/jpg

< ./test.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--
########
POST http://localhost:8080/v1/register
Content-Type: application/json

{
    "email":"nothing12@dot.com",
    "password":"nothing",
    "last_name":"nothing",
    "first_name":"dot"
}
############################
POST http://localhost:8080/v1/login
Content-Type: application/json

{
    "email":"nothing@dot.com",
    "password":"nothing",
    "last_name":"nothing",
    "first_name":"dot"
}
##############
GET http://localhost:8080/v1/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjMsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY2MjYwMzEzNywiaWF0IjoxNjYyNTE2NzM3fQ.K0am045bQoANEYZVslCh4LgAlROBa-fuHlqiA1r1nFQ

####
POST http://localhost:8080/v1/restaurant/e532qos8jjM2/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjEsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY2MjY4ODI5OCwiaWF0IjoxNjYyNjAxODk4fQ.MQPIUZX1gskqngsGvvBg-HQBsVpLFVvIBHAnkNF5jcs
####
DELETE  http://localhost:8080/v1/restaurant/e532qos8jjM2/unlike
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjEsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY2MjY4ODI5OCwiaWF0IjoxNjYyNjAxODk4fQ.MQPIUZX1gskqngsGvvBg-HQBsVpLFVvIBHAnkNF5jcs

#############
GET http://localhost:8080/v1/restaurant/e532qos8jjM2/like
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InVzZXJfaWQiOjEsInJvbGUiOiJ1c2VyIn0sImV4cCI6MTY2MjY4ODI5OCwiaWF0IjoxNjYyNjAxODk4fQ.MQPIUZX1gskqngsGvvBg-HQBsVpLFVvIBHAnkNF5jcs