@api=http://localhost:8080/v1/restaurant
POST {{api}} HTTP/1.1
Content-Type: application/json

{
    "name":"1",
    "addr":"here"
}
#######

DELETE {{api}}/3srL5VfG6da7AA HTTP/1.1
####
GET {{api}} HTTP/1.1
Content-Type: application/json

